name: Sorte CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar pytest
      run: |
        pip install pytest

    - name: Rodar teste do jogo
      run: |
        pytest
